-- Per-student assignment variants generated by Gemini during distribution

CREATE TABLE IF NOT EXISTS public.assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    classroom_assignment_id UUID NOT NULL REFERENCES public.classroom_assignments(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    assignment_text TEXT NOT NULL,
    honeypot_phrase TEXT,
    expected_interpretations JSONB NOT NULL DEFAULT '[]',
    mode TEXT NOT NULL CHECK (mode IN ('proactive', 'reactive')),
    hidden_trigger_phrase TEXT,
    wrong_fact_signal TEXT,
    zero_width_encoded_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;

-- Students can only read their own assignment
CREATE POLICY "Students can read their own assignments"
ON public.assignments
FOR SELECT
USING (student_id = auth.uid());

-- Teachers can read assignments belonging to their classrooms
CREATE POLICY "Teachers can read assignments in their classrooms"
ON public.assignments
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.classroom_assignments ca
        JOIN public.classrooms c ON c.id = ca.classroom_id
        WHERE ca.id = assignments.classroom_assignment_id
        AND c.teacher_id = auth.uid()
    )
);

-- Teachers can insert assignments during distribution
CREATE POLICY "Teachers can insert assignments for distribution"
ON public.assignments
FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.classroom_assignments ca
        JOIN public.classrooms c ON c.id = ca.classroom_id
        WHERE ca.id = assignments.classroom_assignment_id
        AND c.teacher_id = auth.uid()
    )
);
